Decorators
Titus-Kiplagat/library-app pull request #2
Opened 2023-11-08 22:58 UTC by Titus-Kiplagat

#### Project requirements:
- Created `Nameable` class
  - It has correct_name method that raises a NotImplementedError
- Changed `Person` class
  - It inherits from `Nameable`
  - Added `correct_name` method that returns the `@name` attribute
- Created `Decorator`
  - It inherits from `Nameable`
  - It accepts `nameable` object as params and assigns it to `@nameable` instance variable
  - Added `correct_name` method that returns the result of the `correct_name` method of the `@nameable`
- Created CapitalizeDecorator and TrimmerDecorator
  - Both of them inherit from the base `Decorator` class
  - Method `correct_name` in `CapitalizeDecorator` capitalizes the output of `@nameable.correct_name`
  - Method `correct_name` in `TrimmerDecorator` trims the word output of `@nameable.correct_name` if it is more than 10 characters

2023-11-08 23:21 UTC, Reem-lab requested changes
# Hi @Titus-Kiplagat, 👋🏻👋🏻 

Great job so far! 🔥✨💯⭐
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- [ ] No Linters error 🚀
- [ ] Followed GitFlow 💯
- [ ] Great for adding the Decrotar class and the other classes👏🏻
- [ ] Descriptive PR 💯


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-08 23:21 UTC, Reem-lab commented on trimmer_decorator.rb
> +  end
- [ ] Great job working on the decorator class so far but I think it would be great if you add a condition that makes sure that the output of @nameable.correct_name has a maximum of 10 characters. If it's longer it should trim the word. so please firstly check the word if it is longer trim if not return it as it is ✅🔥💯🚀 as mentioned in the requirements 💪🏻

![image](https://github.com/Titus-Kiplagat/library-app/assets/58553711/c81dc1ef-1636-449b-8172-91d1ca0a68cd)

2023-11-09 05:57 UTC, Titus-Kiplagat commented on trimmer_decorator.rb
> +  end
Absolutely! I've updated the `correct_name` decorator to enforce a maximum length of 10 characters. If the corrected name exceeds this limit, it will be trimmed to fit. This ensures that all names adhere to the specified requirements. 
Thank you for the suggestion.

2023-11-09 06:06 UTC, DammyShittu approved these changes
Hi @Titus-Kiplagat,

## APPROVED 🟢

## Highlights
✔️ Decorator class features

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-09 16:49 UTC, merged